"""高级设置元数据。按当前 Rime YAML 结构维护受控可视化字段。"""


# ---------------------------------------------------------------------------
# 万象私有：speller/algebra/__patch 挂载顺序元数据
#
# 这不是 Rime 语法，而是高级设置在“重新生成 __patch 列表”时用于保持
# 正则转写执行顺序的业务规则。新增特殊规则时只改这里，不改 Widget。
# ---------------------------------------------------------------------------
ALGEBRA_SCHEME_NAMES = (
    "全拼",
    "自然码",
    "小鹤双拼",
    "微软双拼",
    "搜狗双拼",
    "智能ABC",
    "紫光双拼",
    "拼音加加",
    "国标双拼",
    "自然龙",
    "汉心龙",
    "蓝天双拼",
    "乱序17",
    "大牛双拼",
    "首道双拼",
)

ALGEBRA_AUX_NAMES = ("直接辅助", "间接辅助")
ALGEBRA_TIQUAN_SCHEMES = ("自然码", "小鹤双拼")

# schema 文件 -> wanxiang_algebra.yaml 中的方案命名空间。
ALGEBRA_VARIANT_BY_FILE = {
    "wanxiang.schema.yaml": "base",
    "wanxiang_pro.schema.yaml": "pro",
    "wanxiang_lite.schema.yaml": "lite",
}

ALGEBRA_PATCH_SLOT_ORDER = {
    "pre_scheme": 10,    # 主拼写方案之前：模糊音
    "scheme": 20,        # 主拼写方案
    "post_scheme": 30,   # 主方案之后：14键等
    "aux": 40,           # Pro 辅助码
    "post_aux": 50,      # 辅助码之后：提权等
    "tail": 90,          # 未登记的新扩展
}

ALGEBRA_PATCH_ORDER_RULES = (
    {
        "slot": "pre_scheme",
        "exact": ("wanxiang_algebra:/模糊音",),
        "prefix": ("wanxiang_algebra:/模糊音_",),
    },
    {
        "slot": "scheme",
        "exact": tuple(
            f"wanxiang_algebra:/{variant}/{scheme}"
            for variant in ("base", "pro", "lite")
            for scheme in ALGEBRA_SCHEME_NAMES
        ),
    },
    {
        "slot": "post_scheme",
        "regex": (
            r"^wanxiang_algebra:/(?:[^/]+/)?14(?:键|jian|key)$",
        ),
    },
    {
        "slot": "aux",
        "exact": tuple(
            f"wanxiang_algebra:/pro/{name}"
            for name in ALGEBRA_AUX_NAMES
        ),
    },
    {
        "slot": "post_aux",
        "exact": tuple(
            f"wanxiang_algebra:/{scheme}提权"
            for scheme in ALGEBRA_TIQUAN_SCHEMES
        ),
    },
)


def algebra_patch_slot(path: str):
    """返回 (slot_name, slot_order)；未知规则返回 (None, tail_order)。"""
    import re as _re

    text = str(path or "").strip()
    for rule in ALGEBRA_PATCH_ORDER_RULES:
        if text in rule.get("exact", ()):
            slot = rule["slot"]
            return slot, ALGEBRA_PATCH_SLOT_ORDER[slot]
        if any(text.startswith(prefix) for prefix in rule.get("prefix", ())):
            slot = rule["slot"]
            return slot, ALGEBRA_PATCH_SLOT_ORDER[slot]
        if any(text.endswith(suffix) for suffix in rule.get("suffix", ())):
            slot = rule["slot"]
            return slot, ALGEBRA_PATCH_SLOT_ORDER[slot]
        if any(_re.search(pattern, text) for pattern in rule.get("regex", ())):
            slot = rule["slot"]
            return slot, ALGEBRA_PATCH_SLOT_ORDER[slot]
    return None, ALGEBRA_PATCH_SLOT_ORDER["tail"]


def sort_algebra_patch_items(items, original_items=None):
    """按万象私有槽位稳定排序 algebra patch。

    已登记规则严格归位；未知但原本已存在的规则尽量保留在原有相邻语义槽位之间；
    新增未知规则默认进入 tail。重复项不会被主动去重。
    """
    values = [str(item).strip() for item in (items or []) if str(item).strip()]
    original = [str(item).strip() for item in (original_items or []) if str(item).strip()]

    # 为重复值分配各自的原始 occurrence index。
    positions = {}
    for idx, value in enumerate(original):
        positions.setdefault(value, []).append(idx)
    used = {}

    original_slots = []
    for idx, value in enumerate(original):
        slot_name, slot_order = algebra_patch_slot(value)
        if slot_name is not None:
            original_slots.append((idx, slot_order))

    def original_index(value):
        seq = positions.get(value, ())
        used_count = used.get(value, 0)
        if used_count < len(seq):
            used[value] = used_count + 1
            return seq[used_count]
        return None

    def unknown_order(orig_idx):
        tail = ALGEBRA_PATCH_SLOT_ORDER["tail"]
        if orig_idx is None:
            return float(tail)

        prev_anchor = None
        next_anchor = None
        for idx, order in original_slots:
            if idx < orig_idx:
                prev_anchor = (idx, order)
            elif idx > orig_idx:
                next_anchor = (idx, order)
                break

        if prev_anchor and next_anchor:
            prev_order = prev_anchor[1]
            next_order = next_anchor[1]
            if prev_order < next_order:
                return (prev_order + next_order) / 2.0
            # 原文件中的已知项本身顺序有误时，未知项贴近距离最近的锚点。
            if orig_idx - prev_anchor[0] <= next_anchor[0] - orig_idx:
                return prev_order + 0.25
            return next_order - 0.25
        if prev_anchor:
            return min(prev_anchor[1] + 0.25, tail - 0.25)
        if next_anchor:
            return max(0.0, next_anchor[1] - 0.25)
        return float(tail)

    decorated = []
    for seq_idx, value in enumerate(values):
        slot_name, slot_order = algebra_patch_slot(value)
        orig_idx = original_index(value)
        order = float(slot_order) if slot_name is not None else unknown_order(orig_idx)
        # 同槽位保持输入顺序；未知旧项优先按原顺序稳定排列。
        stable_idx = orig_idx if orig_idx is not None else len(original) + seq_idx
        decorated.append((order, stable_idx, seq_idx, value))

    decorated.sort(key=lambda row: (row[0], row[1], row[2]))
    return [row[3] for row in decorated]

KNOWN_COMPONENTS_DESC = {'lua_processor@*wanxiang.force_upper_aux': '强制大写辅码(固定分词)',
 'lua_processor@*wanxiang.super_processor': '核心(小键盘/退格限制/声调回退)',
 'lua_processor@*wanxiang.partial_commit': '局部提交(Ctrl+1~0)',
 'lua_processor@*wanxiang.super_sequence*P': '手动排序控制(左/右/置顶)',
 'lua_processor@*wanxiang.super_tips': '超级提示(表情/翻译/简码等)',
 'ascii_composer': '处理英文模式及中英切换',
 'recognizer': '特定规则码识别(如网址/反查)',
 'key_binder': '按键绑定(标点翻页等)',
 'lua_processor@*wanxiang.key_binder': '正则按键绑定扩展',
 'speller': '拼写处理器(接受按键,编辑输入)',
 'punctuator': '符号处理器',
 'selector': '选字处理器(数字选字/翻页)',
 'navigator': '光标导航移动',
 'express_editor': '编辑器(空格/回车/退格)',
 'ascii_segmentor': '标识英文段落(直接上屏)',
 'matcher': '标识符合recognizer的段落',
 'abc_segmentor': '常规汉字拼音段落',
 'affix_segmentor@wanxiang_reverse': '反查分段器',
 'affix_segmentor@add_user_dict': '自造词分段器',
 'punct_segmentor': '符号段落分段',
 'fallback_segmentor': '兜底分段(必须在最后)',
 'punct_translator': '转换标点符号',
 'script_translator': '主拼音/音节翻译器',
 'lua_translator@*wanxiang.version_display': '输入 /wx 显示版本',
 'lua_translator@*wanxiang.set_schema': '输入 /zrm 等切换方案',
 'lua_translator@*wanxiang.shijian': '农历/日期/时间/节日',
 'lua_translator@*wanxiang.super_calculator': '超级计算器',
 'lua_translator@*wanxiang.input_statistics': '打字统计(日/周/月)',
 'table_translator@custom_phrase': '自定义短语(短语置顶)',
 'table_translator@wanxiang_english': '英文词汇表',
 'table_translator@wanxiang_mixedcode': '混合编码词汇表',
 'reverse_lookup_translator@wanxiang_reverse': '反查/辅码翻译',
 'script_translator@user_dict_set': '使用自造词',
 'script_translator@add_user_dict': '生成自造词',
 'lua_filter@*wanxiang.auto_phrase': '无感造词/英文造词',
 'lua_filter@*wanxiang.super_lookup': '反查辅助筛选',
 'lua_filter@*wanxiang.charset_filter': '字符集过滤',
 'lua_filter@*wanxiang.super_replacer': 'OpenCC(简繁/Emoji/简码等)',
 'lua_filter@*wanxiang.super_filter': '综合前置过滤',
 'lua_filter@*wanxiang.super_comment_preedit': '超级注释(辅码/拆分显示)',
 'lua_filter@*wanxiang.super_sequence*F': '手动调序固化过滤',
 'uniquifier': '全局去重(必须在最后)',
 'a': '方括号 []',
 'b': '黑方头括号 【】',
 'c': '双大括号 ❲❳',
 'd': '方头括号 〔〕',
 'e': '小圆括号 ⟮⟯',
 'f': '双方括号 ⟦⟧',
 'g': '直角引号 「」',
 'i': '双直角引号 『』',
 'j': '尖括号 <>',
 'k': '书名号(双) 《》',
 'l': '书名号(单) 〈〉',
 'q': '圆括号 ()',
 'z': '花括号 {}',
 'dy': "英文单引号 ''",
 'sy': '英文双引号 ""',
 'zs': '中文双引号 “”',
 'zd': '中文单引号 ‘’',
 'fy': '反引号 ``',
 'md': 'Markdown 粗体 **|**',
 'jc': '加粗 **|**',
 'it': '斜体 __|__',
 'st': '删除线 ~~|~~',
 'eq': '高亮 ==|==',
 'ln': '行内代码 `|`',
 'cb': '代码块 ```|```',
 'qt': '引用 > |',
 'ul': '无序列表项 - |',
 'ol': '有序列表项 1. |',
 'lk': '链接 [|](url)',
 'im': '图片 ![|](img)',
 'h': '一级标题 # |',
 'hh': '二级标题 ## |',
 'hhh': '三级标题 ### |',
 'hhhh': '四级标题 #### |',
 'br': '换行 |  ',
 '1': '数字键 1 映射',
 '2': '数字键 2 映射',
 '3': '数字键 3 映射',
 '4': '数字键 4 映射',
 '5': '数字键 5 映射',
 '6': '数字键 6 映射',
 '7': '数字键 7 映射',
 '8': '数字键 8 映射',
 '9': '数字键 9 映射',
 '0': '数字键 0 映射',
 'lua_processor@*wanxiang.super_english*P': '英文语句流按键处理器',
 'lua_translator@*wanxiang.super_english*T': '英文词汇限流与格式化翻译器',
 'lua_processor@*wanxiang.context_reorder*P': '上下文调频处理器',
 'lua_filter@*wanxiang.context_reorder*F': '上下文调频过滤器',
 'lua_processor@*wanxiang.unicode_conversion*P': 'Unicode 转换处理器',
 'lua_translator@*wanxiang.unicode_conversion*T': 'Unicode 转换翻译器',
 'lua_translator@*wanxiang.number_conversion': '数字金额转换',
 'lua_translator@*wanxiang.random_tools': 'UUID/ULID/密码等随机工具',
 'lua_translator@*wanxiang.super_symbols': '超级符号与表情翻译器',
 'lua_filter@*wanxiang.super_english*F': '英文语句流格式化过滤器',
 't9_processor': 'T9i 九宫格按键处理器'}

SCHEMA_META_CONFIG = {'schema_info_base': {'_root_key': 'schema',
                      '_match_file': 'wanxiang.schema.yaml',
                      '_title': '🏷️ 方案信息与扩展挂接 (Base版)',
                      '_desc': '万象 Base 主方案的基础属性与依赖。',
                      'nodes': {'schema_id': {'title': '方案标识 (schema_id)', 'type': 'str', 'desc': '应与方案文件名对应，通常不要修改'},
                                'name': {'title': '方案显示名称', 'type': 'str', 'desc': '默认：万象拼音'},
                                'version': {'title': '方案版本号', 'type': 'str', 'desc': '默认：LTS'},
                                'author': {'title': '作者列表', 'type': 'list_text', 'desc': '每行一个作者；保存时保持 YAML 数组类型'},
                                'description': {'title': '方案说明', 'type': 'multiline_str', 'desc': '保持 YAML 多行字符串'},
                                'dependencies': {'title': '扩展方案挂接',
                                                 'type': 'list_text',
                                                 'desc': '每行一个依赖方案；空列表/空值表示无依赖'}}},
 'schema_info_pro': {'_root_key': 'schema',
                     '_match_file': 'wanxiang_pro.schema.yaml',
                     '_title': '🏷️ 方案信息与扩展挂接 (Pro增强版)',
                     '_desc': '万象 Pro 主方案的基础属性与依赖。',
                     'nodes': {'schema_id': {'title': '方案标识 (schema_id)', 'type': 'str', 'desc': '应与方案文件名对应，通常不要修改'},
                               'name': {'title': '方案显示名称', 'type': 'str', 'desc': '默认：万象拼音PRO'},
                               'version': {'title': '方案版本号', 'type': 'str', 'desc': '默认：LTS'},
                               'author': {'title': '作者列表', 'type': 'list_text', 'desc': '每行一个作者；保存时保持 YAML 数组类型'},
                               'description': {'title': '方案说明', 'type': 'multiline_str', 'desc': '保持 YAML 多行字符串'},
                               'dependencies': {'title': '扩展方案挂接',
                                                'type': 'list_text',
                                                'desc': '每行一个依赖方案；空列表/空值表示无依赖'}}},
 'schema_info_lite': {'_root_key': 'schema',
                      '_match_file': 'wanxiang_lite.schema.yaml',
                      '_title': '🏷️ 方案信息与扩展挂接 (Lite轻量版)',
                      '_desc': '万象 Lite 主方案的基础属性与依赖。',
                      'nodes': {'schema_id': {'title': '方案标识 (schema_id)', 'type': 'str', 'desc': '应与方案文件名对应，通常不要修改'},
                                'name': {'title': '方案显示名称', 'type': 'str', 'desc': '默认：万象拼音Lite'},
                                'version': {'title': '方案版本号', 'type': 'str', 'desc': '默认：LTS'},
                                'author': {'title': '作者列表', 'type': 'list_text', 'desc': '每行一个作者；保存时保持 YAML 数组类型'},
                                'description': {'title': '方案说明', 'type': 'multiline_str', 'desc': '保持 YAML 多行字符串'},
                                'dependencies': {'title': '扩展方案挂接',
                                                 'type': 'list_text',
                                                 'desc': '每行一个依赖方案；空列表/空值表示无依赖'}}},
 'schema_info_t9': {'_root_key': 'schema',
                    '_match_file': 'wanxiang_t9.schema.yaml',
                    '_title': '🏷️ 方案信息 (九宫格 T9)',
                    '_desc': '万象九宫格公共方案的基础属性。',
                    'nodes': {'schema_id': {'title': '方案标识 (schema_id)', 'type': 'str', 'desc': '应与方案文件名对应，通常不要修改'},
                              'name': {'title': '方案显示名称', 'type': 'str', 'desc': '默认：万象九键'},
                              'version': {'title': '方案版本号', 'type': 'str', 'desc': '默认：LTS'},
                              'author': {'title': '作者列表', 'type': 'list_text', 'desc': '每行一个作者；保存时保持 YAML 数组类型'},
                              'description': {'title': '方案说明', 'type': 'multiline_str', 'desc': '保持 YAML 多行字符串'},
                              'dependencies': {'title': '扩展方案挂接',
                                               'type': 'list_text',
                                               'desc': '每行一个依赖方案；空列表/空值表示无依赖'}}},
 'schema_info_t9i': {'_root_key': 'schema',
                     '_match_file': 'wanxiang_t9i.schema.yaml',
                     '_title': '🏷️ 方案信息 (九宫格 T9i/元书)',
                     '_desc': '适用于 iOS 元书/仓技术路线的九宫格方案。',
                     'nodes': {'schema_id': {'title': '方案标识 (schema_id)', 'type': 'str', 'desc': '应与方案文件名对应，通常不要修改'},
                               'name': {'title': '方案显示名称', 'type': 'str', 'desc': '默认：万象九键(元书)'},
                               'version': {'title': '方案版本号', 'type': 'str', 'desc': '默认：LTS'},
                               'author': {'title': '作者列表', 'type': 'list_text', 'desc': '每行一个作者；保存时保持 YAML 数组类型'},
                               'description': {'title': '方案说明', 'type': 'multiline_str', 'desc': '保持 YAML 多行字符串'},
                               'dependencies': {'title': '扩展方案挂接',
                                                'type': 'list_text',
                                                'desc': '每行一个依赖方案；空列表/空值表示无依赖'}}},
 'schema_info_mixedcode': {'_root_key': 'schema',
                           '_match_file': 'wanxiang_mixedcode.schema.yaml',
                           '_title': '🏷️ 方案信息 (混合编码 Mixedcode)',
                           '_desc': '定义混合编码方案的基础属性与元数据。',
                           'nodes': {'schema_id': {'title': '方案标识 (schema_id)',
                                                   'type': 'str',
                                                   'desc': '不可随意更改，须与文件名对齐'},
                                     'name': {'title': '方案名称 (name)', 'type': 'str', 'desc': '如: 万象：英文与混合编码'},
                                     'version': {'title': '版本号 (version)', 'type': 'str'},
                                     'author': {'title': '作者 (author)', 'type': 'str'},
                                     'description': {'title': '方案描述 (description)',
                                                     'type': 'str',
                                                     'desc': '简要描述该方案的作用'}}},
 'schema_info_reverse': {'_root_key': 'schema',
                         '_match_file': 'wanxiang_reverse.schema.yaml',
                         '_title': '🏷️ 方案信息 (拆分与笔画反查 Reverse)',
                         '_desc': '定义反查方案的基础属性与元数据。',
                         'nodes': {'schema_id': {'title': '方案标识 (schema_id)',
                                                 'type': 'str',
                                                 'desc': '不可随意更改，须与文件名对齐'},
                                   'name': {'title': '方案名称 (name)', 'type': 'str', 'desc': '如: 万象：拆分与笔画反查'},
                                   'version': {'title': '版本号 (version)', 'type': 'str'},
                                   'author': {'title': '作者 (author)', 'type': 'str'},
                                   'description': {'title': '方案描述 (description)',
                                                   'type': 'str',
                                                   'desc': '简要描述该方案的作用'}}},
 'schema_info_english': {'_root_key': 'schema',
                         '_match_file': 'wanxiang_english.schema.yaml',
                         '_title': '🏷️ 方案信息 (英文 English)',
                         '_desc': '定义英文语句流方案的基础属性与元数据。',
                         'nodes': {'schema_id': {'title': '方案标识 (schema_id)',
                                                 'type': 'str',
                                                 'desc': '不可随意更改，须与文件名对齐'},
                                   'name': {'title': '方案名称 (name)', 'type': 'str', 'desc': '如: 万象英文'},
                                   'version': {'title': '版本号 (version)', 'type': 'str'},
                                   'author': {'title': '作者 (author)', 'type': 'str'},
                                   'description': {'title': '方案描述 (description)',
                                                   'type': 'str',
                                                   'desc': '支持整句输入及格式化...'}}},
 'speller_main': {'_root_key': 'speller',
                  '_match_files': ['wanxiang.schema.yaml', 'wanxiang_pro.schema.yaml', 'wanxiang_lite.schema.yaml'],
                  '_title': '🔤 拼写与运算设定 (speller)',
                  '_desc': 'Base / Pro / Lite 共用拼写字段；algebra 通过万象挂载块管理。',
                  'nodes': {'alphabet': {'title': '有效输入字符', 'type': 'str', 'desc': '定义哪些按键会被输入法接管'},
                            'initials': {'title': '起始字符', 'type': 'str', 'desc': '允许作为输入起点的字符集合'},
                            'delimiter': {'title': '系统分隔符', 'type': 'str', 'desc': '例如空格和单引号'},
                            'algebra/__patch': {'title': '🧩 拼写方案、辅助码与模糊音',
                                                'type': 'algebra_patch',
                                                'baseline': 'source_effective',
                                                'desc': '按正则执行顺序管理主拼写方案、辅助码、模糊音和附加挂载项'}}},
 'speller_t9': {'_root_key': 'speller',
                '_match_files': ['wanxiang_t9.schema.yaml', 'wanxiang_t9i.schema.yaml'],
                '_title': '🔢 九宫格拼写规则 (speller)',
                '_desc': 'T9/T9i 使用直接 algebra 规则列表，不套用 Base/Pro/Lite 的 algebra 挂载器。',
                'nodes': {'alphabet': {'title': '有效输入字符', 'type': 'str'},
                          'initials': {'title': '起始字符', 'type': 'str'},
                          'delimiter': {'title': '系统分隔符', 'type': 'str'},
                          'algebra': {'title': '九宫格正则转写链', 'type': 'dynamic_list', 'desc': '按当前顺序逐条执行；顺序会影响九键编码转换'}}},
 'speller_reverse': {'_root_key': 'speller',
                     '_match_file': 'wanxiang_reverse.schema.yaml',
                     '_title': '🔤 反查拼写与运算 (speller)',
                     '_desc': '配置反查方案独有的拼音解析与笔画规则。',
                     'nodes': {'algebra': {'title': '🧩 反查拼音与笔画方案',
                                           'type': 'reverse_algebra',
                                           'baseline': 'source_effective',
                                           'desc': '智能配置反查拼音解析类型与笔画打法'}}},
 'speller_english': {'_root_key': 'speller',
                     '_match_file': 'wanxiang_english.schema.yaml',
                     '_title': '🔤 英文拼写与运算 (speller)',
                     '_desc': '配置英文方案独有的通用规则与按键映射。',
                     'nodes': {'algebra': {'title': '🧩 英文按键映射方案',
                                           'type': 'english_algebra',
                                           'baseline': 'source_effective',
                                           'desc': '智能配置英文状态下的按键映射打法'}}},
 'speller_mixed': {'_root_key': 'speller',
                   '_match_file': 'wanxiang_mixedcode.schema.yaml',
                   '_title': '🔤 混合拼写与运算 (speller)',
                   '_desc': '配置混合编码方案独有的通用派生规则与按键映射。',
                   'nodes': {'algebra': {'title': '🧩 混合按键映射方案',
                                         'type': 'mixed_algebra',
                                         'baseline': 'source_effective',
                                         'desc': '智能配置混合状态下的按键映射打法'}}},
 'punctuator': {'_root_key': 'punctuator',
                '_title': '🔣 标点与符号入口 (punctuator)',
                '_desc': '管理数字分隔符、符号表导入以及符号补丁来源。',
                'nodes': {'digit_separators': {'title': '数字分隔符', 'type': 'str', 'desc': '当前默认：,.:'},
                          '__include': {'title': '符号表导入 (__include)',
                                        'type': 'raw_yaml',
                                        'baseline': 'source_effective',
                                        'desc': '既支持单个引用，也支持 YAML 列表或映射'},
                          '__patch': {'title': '符号补丁 (__patch)',
                                      'type': 'raw_yaml',
                                      'baseline': 'source_effective',
                                      'desc': '既支持单个引用，也支持 custom 中的列表形式'}}},
 'switches': {'_root_key': 'switches',
              '_title': '🎛️ 状态开关 (switches)',
              '_desc': '定义输入法的状态切换开关（如中英文、繁简、标点等）。支持拖拽排序。',
              'nodes': {'__self__': {'title': '开关配置块',
                                     'type': 'dynamic_block_list',
                                     'desc': '添加或修改开关。【注意】：单开关填 name，多开关组填 options，二选一即可！',
                                     'template': {'name': {'title': '单开关标识 (name)',
                                                           'type': 'str',
                                                           'desc': '如: ascii_mode (与 options 二选一)'},
                                                  'options': {'title': '多开关组 (options)',
                                                              'type': 'list_text',
                                                              'desc': '如: [s2s, s2t, s2hk]'},
                                                  'states': {'title': '菜单显示名称 (states)',
                                                             'type': 'list_text',
                                                             'desc': '如: [简体, 通繁, 港繁]'},
                                                  'reset': {'title': '默认状态索引 (reset)',
                                                            'type': 'int',
                                                            'desc': '重置到的默认项(从 0 开始)。留空则不重置'}}}}},
 'engine': {'_root_key': 'engine',
            '_title': '🚀 引擎组件树 (engine)',
            '_desc': '动态管理底层处理单元，悬浮行支持自由添加、移动、删除组件。',
            'nodes': {'processors': {'title': '处理器 (Processors)', 'type': 'dynamic_list', 'desc': '打字按键拦截与基础逻辑处理'},
                      'segmentors': {'title': '分段器 (Segmentors)', 'type': 'dynamic_list', 'desc': '对输入的编码段落进行标签化'},
                      'translators': {'title': '翻译器 (Translators)',
                                      'type': 'dynamic_list',
                                      'desc': '将不同标签的编码翻译为候选文字'},
                      'filters': {'title': '过滤器 (Filters)', 'type': 'dynamic_list', 'desc': '对最终的候选词进行修饰、去重与调序'}}},
 'translator': {'_root_key': 'translator',
                '_title': '🔤 主翻译器配置 (translator)',
                '_desc': '自由增减核心参数。点击 ➕ 号添加，在左侧下拉框中选择要启用的功能，右侧填写对应值。\n【提示】true/false直接填。不需要的参数直接点 ❌ 删除即可！',
                'nodes': {'__self__': {'title': '已启用的参数',
                                       'type': 'dynamic_kv_list',
                                       'preset_keys': {'dictionary': '挂载主词库名 (填字符串)',
                                                       'prism': '独立棱镜/缓存名 (T9/T9i 使用)',
                                                       'enable_completion': '启用候选词补全 (true/false)',
                                                       'enable_user_dict': '启用用户词典/自动调频 (true/false)',
                                                       'enable_sentence': '启用自动造句 (true/false)',
                                                       'enable_correction': '启用纠错 (true/false)',
                                                       'encode_commit_history': '记录上屏历史参与编码 (true/false)',
                                                       'contextual_suggestions': '上下文建议 (true/false)',
                                                       'core_word_length': '核心词组长度 (数字)',
                                                       'max_word_length': '最大词组长度 (数字)',
                                                       'max_homophones': '最大同音词数 (数字)',
                                                       'initial_quality': '初始质量权重 (数字)',
                                                       'spelling_hints': '拼写提示最大长度 (数字)',
                                                       'always_show_comments': '强制始终显示注释 (true/false)',
                                                       'comment_format': '注释格式化规则 (填列表)'}}}},
 'custom_phrase': {'_root_key': 'custom_phrase',
                   '_title': '📝 自定义短语 (custom_phrase)',
                   '_desc': '定义打字时优先上屏的快捷短语与权重。',
                   'nodes': {'dictionary': {'title': '挂载词库', 'type': 'str', 'desc': '通常留空'},
                             'user_dict': {'title': '用户词典名', 'type': 'str', 'desc': '默认: custom_phrase'},
                             'db_class': {'title': '数据库类型',
                                          'type': 'select',
                                          'options': ['stabledb', 'tabledb', 'userdb'],
                                          'desc': '默认: stabledb'},
                             'enable_completion': {'title': '开启补全提示', 'type': 'bool'},
                             'enable_sentence': {'title': '开启自动造句', 'type': 'bool'},
                             'initial_quality': {'title': '初始权重值', 'type': 'int', 'desc': '设为 99 可让短语置顶'}},
                   '_match_files': ['wanxiang.schema.yaml', 'wanxiang_pro.schema.yaml', 'wanxiang_lite.schema.yaml']},
 'wanxiang_english': {'_root_key': 'wanxiang_english',
                      '_title': '🔤 英文混输与造词 (wanxiang_english)',
                      '_desc': '处理英文模式、中英混输空格策略及英文自动造词。',
                      'nodes': {'dictionary': {'title': '挂载英文词库', 'type': 'str'},
                                'user_dict': {'title': '英文用户词典', 'type': 'str', 'desc': '默认: en'},
                                'enable_completion': {'title': '开启补全提示', 'type': 'bool'},
                                'enable_sentence': {'title': '开启自动造句', 'type': 'bool'},
                                'initial_quality': {'title': '初始权重值', 'type': 'float', 'desc': '如: 2.1'},
                                'comment_format': {'title': '注释格式化规则', 'type': 'list_text', 'desc': '去除带声调字母防崩溃'},
                                'english_spacing': {'title': '自动加空格模式',
                                                    'type': 'select',
                                                    'options': ['smart', 'off', 'before', 'after'],
                                                    'desc': 'smart: 智能加空格'},
                                'spacing_timeout': {'title': '空格状态超时(秒)', 'type': 'int', 'desc': '0为不超时'},
                                'max_candidates': {'title': '最大候选数', 'type': 'int', 'desc': '英文候选输出最大数量'},
                                'trigger': {'title': '英文造词触发符', 'type': 'str', 'desc': '默认: \\ (双击生效)'}},
                      '_match_files': ['wanxiang.schema.yaml',
                                       'wanxiang_pro.schema.yaml',
                                       'wanxiang_lite.schema.yaml']},
 'wanxiang_mixedcode': {'_root_key': 'wanxiang_mixedcode',
                        '_title': '🔣 混合编码表 (wanxiang_mixedcode)',
                        '_desc': '处理中文、英文、数字、符号等混合词汇上屏。',
                        'nodes': {'dictionary': {'title': '挂载混合词库', 'type': 'str'},
                                  'db_class': {'title': '数据库类型',
                                               'type': 'select',
                                               'options': ['stabledb', 'tabledb', 'userdb']},
                                  'enable_completion': {'title': '开启补全提示', 'type': 'bool'},
                                  'enable_sentence': {'title': '开启自动造句', 'type': 'bool'},
                                  'initial_quality': {'title': '初始权重值', 'type': 'int'},
                                  'comment_format': {'title': '注释格式化规则', 'type': 'list_text', 'desc': '去除带声调字母防崩溃'}},
                        '_match_files': ['wanxiang.schema.yaml',
                                         'wanxiang_pro.schema.yaml',
                                         'wanxiang_lite.schema.yaml']},
 'wanxiang_reverse': {'_root_key': 'wanxiang_reverse',
                      '_title': '🔍 部件拆字反查 (wanxiang_reverse)',
                      '_desc': '提供拼音反查部件、笔画等的入口配置。',
                      'nodes': {'tag': {'title': '反查生效标签', 'type': 'str'},
                                'dictionary': {'title': '挂载反查词库', 'type': 'str'},
                                'enable_completion': {'title': '开启补全提示', 'type': 'bool'},
                                'prefix': {'title': '反查触发前缀', 'type': 'str', 'desc': '默认: ` (反引号)'},
                                'tips': {'title': '反查提示语', 'type': 'str', 'desc': '如: 〔反查：拆分|笔画〕'}},
                      '_match_files': ['wanxiang.schema.yaml',
                                       'wanxiang_pro.schema.yaml',
                                       'wanxiang_lite.schema.yaml']},
 'wanxiang_lookup': {'_root_key': 'wanxiang_lookup',
                     '_title': '🔎 反查辅助筛选 (wanxiang_lookup)',
                     '_desc': '控制 super_lookup.lua 反查滤镜的行为、引导符及声调支持。',
                     'nodes': {'tags': {'title': '生效标签 (tags)',
                                        'type': 'list_text',
                                        'desc': '检索当前tag的候选\n一行填一个，如: abc'},
                               'key': {'title': '反查引导符 (key)',
                                       'type': 'str',
                                       'desc': '默认: ` (需添加到 speller/alphabet 中)'},
                               'lookup': {'title': '反查数据库 (lookup)',
                                          'type': 'list_text',
                                          'desc': '反查滤镜数据库\n一行填一个，如: wanxiang_reverse'},
                               'data_source': {'title': '数据来源 (data_source)',
                                               'type': 'list_text',
                                               'desc': '基础版填 db，Pro版可加 comment'}}},
 'wanxiang_lookup_tone_main': {'_root_key': 'wanxiang_lookup',
                               '_match_files': ['wanxiang.schema.yaml',
                                                'wanxiang_pro.schema.yaml',
                                                'wanxiang_lite.schema.yaml'],
                               '_title': '🔍 拼音反查显示扩展',
                               '_desc': 'Base / Pro / Lite 的声调显示控制。',
                               'nodes': {'enable_tone': {'title': '反查声调显示', 'type': 'bool', 'desc': '控制反查结果是否显示声调'}}},
 'wanxiang_lookup_direct': {'_root_key': 'wanxiang_lookup',
                            '_match_files': ['wanxiang.schema.yaml', 'wanxiang_lite.schema.yaml'],
                            '_title': '🔍 直接反查扩展',
                            '_desc': 'Base / Lite 当前提供直接反查开关。',
                            'nodes': {'enable_direct': {'title': '直接反查', 'type': 'bool', 'desc': '允许直接触发反查逻辑'}}},
 'grammar': {'_root_key': 'grammar',
             '_title': '🧠 语法模型权重 (grammar)',
             '_desc': '控制 LMDG 语法模型的联想行为与惩罚权重（非专业人士建议保持默认）。',
             'nodes': {'language': {'title': '语法模型', 'type': 'str', 'desc': '当前：wanxiang-lts-zh-hans'},
                       'collocation_max_length': {'title': '最大搭配长度', 'type': 'int'},
                       'collocation_min_length': {'title': '最小搭配长度', 'type': 'int'},
                       'collocation_penalty': {'title': '搭配惩罚', 'type': 'int'},
                       'non_collocation_penalty': {'title': '非搭配惩罚', 'type': 'int'},
                       'weak_collocation_penalty': {'title': '弱搭配惩罚', 'type': 'int'},
                       'rear_penalty': {'title': '句尾惩罚', 'type': 'int'}}},
 'super_comment': {'_root_key': 'super_comment',
                   '_title': '📝 超级注释样式 (super_comment)',
                   '_desc': '控制候选注释格式以及各类候选的标识文本。',
                   'nodes': {'candidate_length': {'title': '辅码提醒生效长度', 'type': 'int', 'desc': '0 为关闭'},
                             'corrector_type': {'title': '普通注释格式',
                                                'type': 'str',
                                                'desc': 'comment 占位符必须保留，例如：〔comment〕'},
                             'tone_isolate': {'title': '声调隔离', 'type': 'bool', 'desc': '声调数字是否与普通拼写转换隔离'},
                             'convert_abbrev_preedit': {'title': '简码预编辑转换', 'type': 'bool', 'desc': '是否转换简码候选的预编辑显示'},
                             'cand_type': {'title': '候选类型标识表',
                                           'type': 'dynamic_map',
                                           'desc': '完整展示 schema + custom 的最终键值；支持增加、删除和修改类型'}}},
 'super_processor': {'_root_key': 'super_processor',
                     '_title': '⚙️ 核心处理器 (super_processor)',
                     '_desc': '控制拼音、选词、退格等高级逻辑行为。',
                     'nodes': {'enable_backspace_limit': {'title': '开启退格限制',
                                                          'type': 'bool',
                                                          'desc': '限制退格键越界删除（防止删错上屏词）'},
                               'enable_seg_loop': {'title': '分词符循环', 'type': 'bool', 'desc': '开启后单引号分词符可循环切换'},
                               'enable_tone_fallback': {'title': '声调回退', 'type': 'bool', 'desc': '启用声调输入时的逻辑回退'},
                               'enable_predict_space': {'title': '联想空格打断',
                                                        'type': 'bool',
                                                        'desc': '对齐大厂：空格直接上屏并清空联想'},
                               'kp_number_mode': {'title': '小键盘模式',
                                                  'type': 'select',
                                                  'options': ['auto', 'compose'],
                                                  'desc': 'auto: 自动识别 | compose: 强制组字'},
                               'limit_repeated': {'title': '重复声母限制',
                                                  'type': 'str',
                                                  'desc': '格式：最大重复声母,最大候选字数 (如 8,40)'},
                               'select_character': {'title': '以词定字按键',
                                                    'type': 'str',
                                                    'desc': '默认: [,] (支持括号名或全拼名)'}}},
 'context_reorder': {'_root_key': 'context_reorder',
                     '_match_files': ['wanxiang.schema.yaml',
                                      'wanxiang_pro.schema.yaml',
                                      'wanxiang_t9.schema.yaml',
                                      'wanxiang_t9i.schema.yaml'],
                     '_title': '🧠 上下文调频 (context_reorder)',
                     '_desc': '当前上下文调频模块；替代已删除的 user_predict 配置段。',
                     'nodes': {'db_name': {'title': '数据库名称', 'type': 'str', 'desc': '默认：context_reorder'},
                               'enable_fallback_reorder': {'title': '同码回删再输入交换', 'type': 'bool'},
                               'context_timeout': {'title': '上下文超时（毫秒）', 'type': 'int'},
                               'custom_classifiers': {'title': '数字后分类器',
                                                      'type': 'list_text',
                                                      'desc': '每行一组量词/分类字符'}}},
 'super_tips': {'_root_key': 'super_tips',
                '_title': '💡 超级提示模块 (super_tips)',
                '_desc': '控制实时提示数据的路径与触发按键。',
                'nodes': {'db_name': {'title': '数据库路径', 'type': 'str', 'desc': '默认：lua/tips'},
                          'tips_key': {'title': '提示上屏按键', 'type': 'str', 'desc': '默认：comma'},
                          'files': {'title': '提示数据文件', 'type': 'list_text', 'desc': '每行一个文件路径；保持 YAML 数组类型'},
                          'disabled_types': {'title': '🚫 屏蔽的提示类型', 'type': 'list_text', 'desc': '每行一个类型'}}},
 'super_symbols': {'_root_key': 'super_symbols',
                   '_title': '✨ 超级符号库 (super_symbols)',
                   '_desc': '管理符号/表情前缀、数据文件、候选数和 custom 可扩展触发器。',
                   'nodes': {'prefix_sym': {'title': '符号精确前缀', 'type': 'str', 'desc': '默认：/sym'},
                             'prefix_emoji': {'title': '表情精确前缀', 'type': 'str', 'desc': '默认：/emoji'},
                             'max_candidates': {'title': '最大候选数', 'type': 'int'},
                             'data_sym': {'title': '符号数据文件', 'type': 'str'},
                             'data_emoji': {'title': '表情数据文件', 'type': 'str'}},
                   '_match_files': ['wanxiang.schema.yaml', 'wanxiang_pro.schema.yaml']},
 'super_sequence': {'_root_key': 'super_sequence',
                    '_title': '↕️ 手动排序 (super_sequence)',
                    '_desc': '控制候选项的手动调序与置顶按键',
                    'nodes': {'db_name': {'title': '数据库路径', 'type': 'str', 'desc': '默认为 lua/sequence'},
                              'up': {'title': '向前移动快捷键', 'type': 'str', 'desc': '默认：Control+j'},
                              'down': {'title': '向后移动快捷键', 'type': 'str', 'desc': '默认：Control+k'},
                              'reset': {'title': '重置位移快捷键', 'type': 'str', 'desc': '默认：Control+l'},
                              'pin': {'title': '置顶候选快捷键', 'type': 'str', 'desc': '默认：Control+p'}},
                    '_match_files': ['wanxiang.schema.yaml', 'wanxiang_pro.schema.yaml']},
 'super_replacer': {'_root_key': 'super_replacer',
                    '_title': '🔄 超级替代器 (super_replacer)',
                    '_desc': '深度定制过滤与替换逻辑。区块支持任意添加、移动、删除。',
                    'nodes': {'db_name': {'title': '数据库路径', 'type': 'str', 'desc': '默认: lua/replacer'},
                              'comment_format': {'title': '注释格式', 'type': 'str', 'desc': '默认: 〔%s〕'},
                              'chain': {'title': '流水线模式', 'type': 'bool', 'desc': '开启后上一个结果会传给下一个'},
                              'rules': {'title': '📑 规则链条 (Rules)',
                                        'type': 'dynamic_block_list',
                                        'desc': '按自上而下的顺序执行的替换/滤镜规则块',
                                        'template': {'option': {'title': '绑定开关',
                                                                'type': 'list_text',
                                                                'desc': '单开关、true，或数组 [s2t, s2hk]'},
                                                     'cand_type': {'title': '候选类型',
                                                                   'type': 'str',
                                                                   'desc': '如: emoji, abbrev'},
                                                     'mode': {'title': '处理模式',
                                                              'type': 'select',
                                                              'options': ['append', 'replace', 'comment', 'abbrev']},
                                                     'comment_mode': {'title': '注释模式',
                                                                      'type': 'select',
                                                                      'options': ['none', 'append', 'text'],
                                                                      'visible_if': {'mode': ['append', 'replace']}},
                                                     'sentence': {'title': '整句转换',
                                                                  'type': 'bool',
                                                                  'visible_if': {'mode': ['append', 'replace']}},
                                                     'tags': {'title': '生效标签',
                                                              'type': 'list_text',
                                                              'desc': '如: [abc]'},
                                                     'prefix': {'title': '数据前缀', 'type': 'str', 'desc': '如: _em_'},
                                                     'abbrev_rule': {'title': '简码置顶规则',
                                                                     'type': 'str',
                                                                     'desc': '如: 1,6 或 2,3',
                                                                     'visible_if': {'mode': ['abbrev']}},
                                                     't9_optimization': {'title': 'T9编码优化',
                                                                         'type': 'bool',
                                                                         'desc': '将字母转为数字编码',
                                                                         'visible_if': {'mode': ['abbrev']}},
                                                     'files': {'title': '字典文件',
                                                               'type': 'list_text',
                                                               'desc': '每行一个文件路径'},
                                                     'exclude_types': {'title': '排除输入类型',
                                                                       'type': 'list_text',
                                                                       'desc': '例如：[pinyin]；这些输入类型不执行本规则'}}}}},
 'charset_filter': {'_root_key': 'charset_filter',
                    '_match_files': ['wanxiang.schema.yaml',
                                     'wanxiang_pro.schema.yaml',
                                     'wanxiang_t9.schema.yaml',
                                     'wanxiang_t9i.schema.yaml'],
                    '_title': '🔤 字符集过滤 (charset_filter)',
                    '_desc': '按开关分别配置基础字符集、增补白名单与黑名单。',
                    'nodes': {'__self__': {'title': '过滤规则组',
                                           'type': 'dynamic_block_list',
                                           'desc': '规则按列表顺序保存；可增删、移动。',
                                           'template': {'option': {'title': '绑定开关',
                                                                   'type': 'str',
                                                                   'desc': '如 charset_filter / s2t / s2hk / s2tw'},
                                                        'base': {'title': '基础字符集',
                                                                 'type': 'str',
                                                                 'desc': '例如 a / fa / ha / ta'},
                                                        'addlist': {'title': '白名单（增补）',
                                                                    'type': 'list_text',
                                                                    'desc': '每行一项；也支持 YAML 数组'},
                                                        'blacklist': {'title': '黑名单（剔除）',
                                                                      'type': 'list_text',
                                                                      'desc': '每行一项；也支持 YAML 数组'}}}}},
 'unicode': {'_root_key': 'unicode',
             '_match_files': ['wanxiang.schema.yaml', 'wanxiang_pro.schema.yaml', 'wanxiang_lite.schema.yaml'],
             '_title': '🔣 Unicode 转换 (unicode)',
             '_desc': 'Unicode 转换模块的触发按键。',
             'nodes': {'key': {'title': 'Unicode 快捷键', 'type': 'str', 'desc': '当前默认：Control+u'}}},
 'random_tools': {'_root_key': 'random_tools',
                  '_match_files': ['wanxiang.schema.yaml', 'wanxiang_pro.schema.yaml', 'wanxiang_lite.schema.yaml'],
                  '_title': '🎲 随机工具 (random_tools)',
                  '_desc': 'UUID / ULID / 密码等随机工具触发码及字符集。',
                  'nodes': {'uuid': {'title': 'UUID v4 触发码', 'type': 'str'},
                            'uuid7': {'title': 'UUID v7 触发码', 'type': 'str'},
                            'ulid': {'title': 'ULID 触发码', 'type': 'str'},
                            'password': {'title': '密码触发码', 'type': 'str'},
                            'password_special': {'title': '特殊字符密码触发码', 'type': 'str'},
                            'password_lengths': {'title': '密码长度列表', 'type': 'str', 'desc': '例如：6,8,10,16'},
                            'chars': {'title': '随机字符池',
                                      'type': 'dynamic_map',
                                      'desc': 'upper/lower/digit/special 等字符池'}}},
 'random_tools_lite_extra': {'_root_key': 'random_tools',
                             '_match_file': 'wanxiang_lite.schema.yaml',
                             '_title': '🎲 Lite PIN 扩展',
                             '_desc': 'Lite 额外提供 PIN 长度设置。',
                             'nodes': {'pin_lengths': {'title': 'PIN 长度列表', 'type': 'str', 'desc': '例如：4,6,8,10'}}},
 'input_stats': {'_root_key': 'input_stats',
                 '_title': '📊 打字效率统计 (input_stats)',
                 '_desc': '管理统计数据库与触发码映射。',
                 'nodes': {'db_name': {'title': '数据库路径', 'type': 'str', 'desc': '例如：lua/stats'},
                           'triggers': {'title': '统计触发码映射',
                                        'type': 'dynamic_map',
                                        'desc': '完整展示 clear/today/week/month/year/total/history，也支持 custom 新增触发项'}}},
 'date_formats': {'_root_key': 'date_formats',
                  '_title': '📅 日期格式化 (date_formats)',
                  '_desc': '触发码: orq, /rq, N日期 等。\n【占位符】 Y:四位年 | y:两位年 | m:月(带零) | n:月(无零) | d:日(带零) | j:日(无零)',
                  'nodes': {'__self__': {'title': '可选格式列表',
                                         'type': 'dynamic_list',
                                         'desc': '向下排序对应打字时的候选 1, 2, 3...'}}},
 'time_formats': {'_root_key': 'time_formats',
                  '_title': '🕒 时间格式化 (time_formats)',
                  '_desc': '触发码: osj, /sj 等。\n'
                           '【占位符】 H:24时(带零) | G:24时(无零) | I:12时(带零) | l:12时(无零) | M:分 | S:秒\n'
                           '【标识符】 p:am/pm | P:AM/PM | A:凌晨/上午/中午/下午/晚上',
                  'nodes': {'__self__': {'title': '可选格式列表',
                                         'type': 'dynamic_list',
                                         'desc': '向下排序对应打字时的候选 1, 2, 3...'}}},
 'datetime_formats': {'_root_key': 'datetime_formats',
                      '_title': '🕙 完整日期时间组合 (datetime_formats)',
                      '_desc': '触发码: odt, /dt, /tt 等。\n'
                               '【时区占位】 O:带冒号(+08:00) | o:无冒号(+0800)\n'
                               '【高级语法】 支持 \\X 转义单个字符，或 [[...]] 整体原样输出',
                      'nodes': {'__self__': {'title': '可选格式列表',
                                             'type': 'dynamic_list',
                                             'desc': '向下排序对应打字时的候选 1, 2, 3...'}}},
 'english_date_formats': {'_root_key': 'english_date_formats',
                          '_match_files': ['wanxiang.schema.yaml',
                                           'wanxiang_pro.schema.yaml',
                                           'wanxiang_lite.schema.yaml',
                                           'wanxiang_t9.schema.yaml',
                                           'wanxiang_t9i.schema.yaml'],
                          '_title': '📅 英文日期格式 (english_date_formats)',
                          '_desc': '英文日期候选格式，按列表顺序输出。',
                          'nodes': {'__self__': {'title': '英文日期格式列表',
                                                 'type': 'dynamic_list',
                                                 'desc': '例如 B j, Y / j b Y / Y-m-d'}}},
 'quick_symbol_text': {'_root_key': 'quick_symbol_text',
                       '_title': '⚡ 单字母快符 (quick_symbol_text)',
                       '_desc': '通过触发正则和字符映射实现单字母快捷符号；以最终 effective 配置展示。',
                       'nodes': {'trigger': {'title': '触发正则表达式', 'type': 'str', 'desc': '默认：^([a-z])/$'},
                                 'symkey': {'title': '快捷符号映射表',
                                            'type': 'dynamic_map',
                                            'desc': '支持 schema/custom 增加、删除或修改任意键值；repeat 表示重复上屏'}},
                       '_match_files': ['wanxiang.schema.yaml',
                                        'wanxiang_pro.schema.yaml',
                                        'wanxiang_lite.schema.yaml']},
 'paired_symbols': {'_root_key': 'paired_symbols',
                    '_title': '🔠 成对符号包裹 (paired_symbols)',
                    '_desc': '输入引导键(默认为 \\)触发包裹，如输入 nihao\\c 将候选[你好]变为 ❲你好❳。\n'
                             '【语法】支持使用 | 明确区分前后(如 **|**)，没有 | 则默认各分一半。',
                    'nodes': {'trigger': {'title': '触发引导符', 'type': 'str', 'desc': '默认: \\ (提示: 填单反斜杠即可)'},
                              'symkey': {'title': '包裹规则映射表',
                                         'type': 'dynamic_map',
                                         'desc': '格式必须为【键: 值】(如 md: **|**)。支持任意修改Key和Value！'}},
                    '_match_files': ['wanxiang.schema.yaml',
                                     'wanxiang_pro.schema.yaml',
                                     'wanxiang_lite.schema.yaml']},
 'recognizer': {'_root_key': 'recognizer',
                '_title': '🎯 正则识别器 (recognizer)',
                '_desc': '处理符合特定规则的输入码，如网址、反查、特定前缀引导等。',
                'nodes': {'import_preset': {'title': '继承预设', 'type': 'str', 'desc': '默认: default'},
                          'patterns': {'title': '触发规则表 (patterns)',
                                       'type': 'dynamic_map',
                                       'desc': '格式必须为【键: 值】。值为正则表达式，支持任意增减和修改键名。'}}},
 'key_binder': {'_root_key': 'key_binder',
                '_title': '⌨️ 快捷键与宏绑定 (key_binder)',
                '_desc': '自定义快捷键，支持翻页、方案切换、功能开关及按键宏(宏序列)。',
                'nodes': {'import_preset': {'title': '继承预设', 'type': 'str', 'desc': '默认: default'},
                          'shijian_keys': {'title': '时间引导符', 'type': 'list_text', 'desc': '如 / 或 o，每行一个'},
                          'bindings': {'title': '按键映射表 (bindings)',
                                       'type': 'dynamic_block_list',
                                       'desc': '添加或修改快捷键绑定。【注意】：条件和动作在各自的下拉框选一个即可！',
                                       'template': {'accept': {'title': '触发按键 (accept)',
                                                               'type': 'str',
                                                               'desc': '如 Control+a 或 minus'},
                                                    '_condition': {'title': '触发条件',
                                                                   'type': 'action_kv',
                                                                   'preset_keys': {'when': '状态条件 '
                                                                                           '(always/has_menu/composing/paging)',
                                                                                   'match': '正则匹配 (如 ^/$)'}},
                                                    '_action': {'title': '执行动作',
                                                                'type': 'action_kv',
                                                                'preset_keys': {'send': '映射按键 (send)',
                                                                                'toggle': '切换开关 (toggle)',
                                                                                'send_sequence': '发送宏串 '
                                                                                                 '(send_sequence)',
                                                                                'select': '切换方案 (select)'}}}}}},
 'editor': {'_root_key': 'editor',
            '_title': '📝 编辑器行为 (editor)',
            '_desc': '定义打字过程中各种快捷键的系统级处理逻辑（上屏、撤销、删除等）。',
            'nodes': {'bindings/space': {'title': '[ 空格键 ] space',
                                         'type': 'select',
                                         'options': ['confirm',
                                                     'commit_raw_input',
                                                     'commit_script_text',
                                                     'commit_comment']},
                      'bindings/Return': {'title': '[ 回车键 ] Return',
                                          'type': 'select',
                                          'options': ['commit_raw_input',
                                                      'confirm',
                                                      'commit_script_text',
                                                      'commit_comment']},
                      'bindings/Control+Return': {'title': '[ Ctrl+回车 ] Control+Return',
                                                  'type': 'select',
                                                  'options': ['commit_script_text',
                                                              'commit_raw_input',
                                                              'confirm',
                                                              'commit_comment']},
                      'bindings/Control+Shift+Return': {'title': '[ Ctrl+Shift+回车 ]',
                                                        'type': 'select',
                                                        'options': ['commit_comment',
                                                                    'commit_script_text',
                                                                    'commit_raw_input',
                                                                    'confirm']},
                      'bindings/BackSpace': {'title': '[ 退格键 ] BackSpace',
                                             'type': 'select',
                                             'options': ['revert', 'back_syllable', 'delete_candidate', 'delete']},
                      'bindings/Delete': {'title': '[ 删除键 ] Delete',
                                          'type': 'select',
                                          'options': ['delete', 'revert', 'back_syllable', 'delete_candidate']},
                      'bindings/Control+BackSpace': {'title': '[ Ctrl+退格 ]',
                                                     'type': 'select',
                                                     'options': ['back_syllable',
                                                                 'revert',
                                                                 'delete',
                                                                 'delete_candidate']},
                      'bindings/Control+Delete': {'title': '[ Ctrl+Delete ]',
                                                  'type': 'select',
                                                  'options': ['delete_candidate',
                                                              'delete',
                                                              'revert',
                                                              'back_syllable']},
                      'bindings/Escape': {'title': '[ Esc键 ] Escape', 'type': 'select', 'options': ['cancel']}},
            '_match_files': ['wanxiang.schema.yaml', 'wanxiang_pro.schema.yaml', 'wanxiang_lite.schema.yaml']},
 'navigator': {'_root_key': 'navigator',
               '_title': '🧭 光标导航器 (navigator)',
               '_desc': '控制光标在拼音编码串中的左右移动与跳转规则。',
               'nodes': {'bindings/Left': {'title': '[ 左方向键 ] Left',
                                           'type': 'select',
                                           'options': ['left_by_char_no_loop',
                                                       'left_by_char',
                                                       'left_by_syllable',
                                                       'left_by_syllable_no_loop',
                                                       'rewind']},
                         'bindings/Right': {'title': '[ 右方向键 ] Right',
                                            'type': 'select',
                                            'options': ['right_by_char_no_loop',
                                                        'right_by_char',
                                                        'right_by_syllable',
                                                        'right_by_syllable_no_loop',
                                                        'forward']},
                         'bindings/Shift+Left': {'title': '[ Shift+左 ] Shift+Left',
                                                 'type': 'select',
                                                 'options': ['left_by_syllable',
                                                             'left_by_syllable_no_loop',
                                                             'left_by_char',
                                                             'left_by_char_no_loop',
                                                             'rewind']},
                         'bindings/Shift+Right': {'title': '[ Shift+右 ] Shift+Right',
                                                  'type': 'select',
                                                  'options': ['right_by_syllable',
                                                              'right_by_syllable_no_loop',
                                                              'right_by_char',
                                                              'right_by_char_no_loop',
                                                              'forward']}},
               '_match_files': ['wanxiang.schema.yaml', 'wanxiang_pro.schema.yaml', 'wanxiang_lite.schema.yaml']},
 'user_dict_set': {'_root_key': 'user_dict_set',
                   '_title': '📕 自造词读取 (user_dict_set)',
                   '_desc': '独立挂载的自定义词典引擎，用于读取和输出你造过的词。',
                   'nodes': {'dictionary': {'title': '挂载主词库 (dictionary)', 'type': 'str', 'desc': '如: wanxiang'},
                             'user_dict': {'title': '自造词库名 (user_dict)',
                                           'type': 'str',
                                           'desc': '默认: zc (对应 zc.userdb)'},
                             'initial_quality': {'title': '初始权重 (initial_quality)',
                                                 'type': 'number',
                                                 'desc': '普通方案可为整数，Pro 方案可为小数，如 2.5'},
                             'enable_completion': {'title': '开启补全提示 (completion)', 'type': 'bool'},
                             'enable_sentence': {'title': '开启自动造句 (sentence)', 'type': 'bool'},
                             'enable_user_dict': {'title': '开启自动调频 (user_dict)', 'type': 'bool'},
                             'contextual_suggestions': {'title': '智能上下文预测',
                                                        'type': 'bool',
                                                        'desc': '若开启预测可能与连续长句冲突，导致组合不如预期'},
                             'spelling_hints': {'title': '拼写提示长度', 'type': 'int'},
                             'max_homophones': {'title': '最大同音词数', 'type': 'int'},
                             'comment_format': {'title': '注释格式化规则', 'type': 'list_text', 'desc': '留空即可'}},
                   '_match_files': ['wanxiang.schema.yaml', 'wanxiang_pro.schema.yaml']},
 'user_dict_set_pro_extra': {'_root_key': 'user_dict_set',
                             '_match_file': 'wanxiang_pro.schema.yaml',
                             '_title': '🧩 Pro 自造词长度参数',
                             '_desc': '仅 Pro 当前方案存在的 user_dict_set 长度限制。',
                             'nodes': {'core_word_length': {'title': '核心词组长度', 'type': 'int'},
                                       'max_word_length': {'title': '最大词组长度', 'type': 'int'}}},
 'add_user_dict': {'_root_key': 'add_user_dict',
                   '_title': '✍️ 动态造词引擎 (add_user_dict)',
                   '_desc': '负责写入自造词。双击前缀进入造词模式，或通过 Lua 脚本实现无感造词。',
                   'nodes': {'tag': {'title': '生效标签 (tag)', 'type': 'str', 'desc': '默认: add_user_dict'},
                             'dictionary': {'title': '挂载主词库 (dictionary)', 'type': 'str', 'desc': '如: wanxiang'},
                             'user_dict': {'title': '目标词库名 (user_dict)', 'type': 'str', 'desc': '默认: zc (生成的词会存入此处)'},
                             'prefix': {'title': '手动造词引导符 (prefix)', 'type': 'str', 'desc': '默认: `` (双击反引号)'},
                             'tips': {'title': '造词提示语 (tips)', 'type': 'str', 'desc': '如: 〔开始造词〕'},
                             'initial_quality': {'title': '初始权重 (initial_quality)', 'type': 'int', 'desc': '默认: -1'},
                             'enable_completion': {'title': '开启补全提示 (completion)',
                                                   'type': 'bool',
                                                   'desc': '提前显示尚未输入完整码的字'},
                             'enable_user_dict': {'title': '开启自动调频 (user_dict)', 'type': 'bool'},
                             'enable_auto_phrase': {'title': '启用 Lua 无感造词',
                                                    'type': 'bool',
                                                    'desc': '模型已有词不造，只造未收录词，需配合 lua'},
                             'spelling_hints': {'title': '拼写提示长度', 'type': 'int'},
                             'comment_format': {'title': '注释格式化规则', 'type': 'list_text', 'desc': '留空即可'}},
                   '_match_files': ['wanxiang.schema.yaml', 'wanxiang_pro.schema.yaml']},
 'tone_preedit': {'_root_key': 'tone_preedit',
                  '_title': '🎵 编码区声调转换 (tone_preedit)',
                  '_desc': '常规状态下输入数字时，自动将其转换为对应的声调字符（由超级 preedit 接管）。\n【语法】格式为【键: 值】(如 7: ¹)。支持通过右侧按钮任意添加、移动、删除！',
                  'nodes': {'__self__': {'title': '声调转换映射表', 'type': 'dynamic_map', 'desc': '输入如 7: ¹，保存后自动生效。'}},
                  '_match_files': ['wanxiang.schema.yaml', 'wanxiang_pro.schema.yaml', 'wanxiang_lite.schema.yaml']},
 'force_upper_aux': {'_root_key': 'force_upper_aux',
                     '_title': '🅰️ 强制大写辅码(句中固定) (force_upper_aux)',
                     '_desc': '控制强制大写辅码（固定候选）的快捷键与视觉替代符号。',
                     'nodes': {'hotkey': {'title': '固定候选快捷键 (hotkey)',
                                          'type': 'str',
                                          'desc': '默认: period (可用组合键或符号，如 Tab)'},
                               'symbol': {'title': '视觉替代符号 (symbol)',
                                          'type': 'str',
                                          'desc': '默认: › (用于避免双大写辅码导致输入提示被拉长)'}},
                     '_match_file': 'wanxiang_pro.schema.yaml'},
 't9_sym': {'_root_key': 't9_sym',
            '_match_files': ['wanxiang_t9.schema.yaml', 'wanxiang_t9i.schema.yaml'],
            '_title': '🔢 T9 符号映射 (t9_sym)',
            '_desc': '九宫格专用符号映射。保留 half_shape/+ 等原始键结构。',
            'nodes': {'__self__': {'title': 'T9 符号映射表',
                                   'type': 'raw_yaml',
                                   'desc': '按 YAML 原结构编辑，避免把 half_shape/+ 误解为普通路径'}}},
 'default_schema_list': {'_root_key': 'schema_list',
                         '_match_file': 'default.yaml',
                         '_title': '📜 启用方案列表 (schema_list)',
                         '_desc': '勾选需要在输入法菜单中切换的方案 (自动扫描目录下所有方案)。',
                         'nodes': {'__self__': {'title': '全局可选方案',
                                                'type': 'schema_checkboxes',
                                                'desc': '智能解析本地方案名称，取消勾选即视为停用'}}},
 'default_menu': {'_root_key': 'menu',
                  '_match_file': 'default.yaml',
                  '_title': '🪟 候选菜单条数 (menu)',
                  '_desc': '全局生效的候选词数量与选词标签设定。',
                  'nodes': {'page_size': {'title': '候选词个数', 'type': 'int', 'desc': '建议: 6'},
                            'alternative_select_labels': {'title': '候选项标签',
                                                          'type': 'list_text',
                                                          'desc': '如: [1, 2, 3] 或者 [⒈, ⒉, ⒊]'},
                            'alternative_select_keys': {'title': '选字按键', 'type': 'str', 'desc': '如: ASDFGHJKL'}}},
 'default_switcher': {'_root_key': 'switcher',
                      '_match_file': 'default.yaml',
                      '_title': '🔁 状态面板设置 (switcher)',
                      '_desc': '控制由快捷键唤出的状态切换面板（记忆开关、标题等）。',
                      'nodes': {'caption': {'title': '面板标题', 'type': 'str', 'desc': '如: 「万象状态面板」'},
                                'fold_options': {'title': '呼出时自动折叠', 'type': 'bool'},
                                'abbreviate_options': {'title': '折叠时缩写显示', 'type': 'bool'},
                                'option_list_separator': {'title': '折叠选项分隔符', 'type': 'str', 'desc': "如: ' / '"},
                                'hotkeys': {'title': '面板呼出快捷键', 'type': 'list_text', 'desc': '如: Control+grave'},
                                'save_options': {'title': '状态记忆开关',
                                                 'type': 'list_text',
                                                 'action_btn': '📥 从主方案自动提取',
                                                 'desc': '自动提取无 reset 状态的有用开关变量，一行一个'}}},
 'default_ascii_composer': {'_root_key': 'ascii_composer',
                            '_match_file': 'default.yaml',
                            '_title': '🔠 中英切换逻辑 (ascii_composer)',
                            '_desc': '定义 Shift / CapsLock 等修饰键的中英文切换行为。',
                            'nodes': {'good_old_caps_lock': {'title': '传统 CapsLock 行为',
                                                             'type': 'bool',
                                                             'desc': 'true: 切换大写, false: 切换中英'},
                                      'switch_key/Caps_Lock': {'title': '[ Caps Lock 键 ]',
                                                               'type': 'select',
                                                               'options': ['clear',
                                                                           'commit_code',
                                                                           'commit_text',
                                                                           'noop']},
                                      'switch_key/Shift_L': {'title': '[ 左 Shift 键 ]',
                                                             'type': 'select',
                                                             'options': ['commit_code',
                                                                         'commit_text',
                                                                         'inline_ascii',
                                                                         'clear',
                                                                         'noop']},
                                      'switch_key/Shift_R': {'title': '[ 右 Shift 键 ]',
                                                             'type': 'select',
                                                             'options': ['commit_code',
                                                                         'commit_text',
                                                                         'inline_ascii',
                                                                         'clear',
                                                                         'noop']},
                                      'switch_key/Control_L': {'title': '[ 左 Ctrl 键 ]',
                                                               'type': 'select',
                                                               'options': ['noop',
                                                                           'commit_code',
                                                                           'commit_text',
                                                                           'inline_ascii',
                                                                           'clear']},
                                      'switch_key/Control_R': {'title': '[ 右 Ctrl 键 ]',
                                                               'type': 'select',
                                                               'options': ['noop',
                                                                           'commit_code',
                                                                           'commit_text',
                                                                           'inline_ascii',
                                                                           'clear']}}}}

FILE_INDEX_META = {'🌍 全局与通用配置': [{'file': 'default.yaml', 'name': '全局默认配置 (default)'},
               {'file': 'wanxiang_algebra.yaml', 'name': '拼写运算规则 (algebra)'}],
 '👑 主输入方案': [{'file': 'wanxiang.schema.yaml', 'name': '基础版主方案 (wanxiang)'},
             {'file': 'wanxiang_pro.schema.yaml', 'name': '增强版主方案 (wanxiang_pro)'},
             {'file': 'wanxiang_lite.schema.yaml', 'name': '轻量版主方案 (wanxiang_lite)'}],
 '📱 九宫格方案': [{'file': 'wanxiang_t9.schema.yaml', 'name': 'T9 九宫格方案 (t9)'},
             {'file': 'wanxiang_t9i.schema.yaml', 'name': 'T9i / 元书九宫格方案 (t9i)'}],
 '🧩 附属扩展方案': [{'file': 'wanxiang_english.schema.yaml', 'name': '英文方案 (english)'},
              {'file': 'wanxiang_mixedcode.schema.yaml', 'name': '混合编码方案 (mixedcode)'},
              {'file': 'wanxiang_reverse.schema.yaml', 'name': '反查方案 (reverse)'}]}

RIME_KEY_MAP = {' ': 'space',
 '!': 'exclam',
 '"': 'quotedbl',
 '#': 'numbersign',
 '$': 'dollar',
 '%': 'percent',
 '&': 'ampersand',
 "'": 'apostrophe',
 '(': 'parenleft',
 ')': 'parenright',
 '*': 'asterisk',
 '+': 'plus',
 ',': 'comma',
 '-': 'minus',
 '.': 'period',
 '/': 'slash',
 ':': 'colon',
 ';': 'semicolon',
 '<': 'less',
 '=': 'equal',
 '>': 'greater',
 '?': 'question',
 '@': 'at',
 '[': 'bracketleft',
 '\\': 'backslash',
 ']': 'bracketright',
 '^': 'asciicircum',
 '_': 'underscore',
 '`': 'grave',
 '{': 'braceleft',
 '|': 'bar',
 '}': 'braceright',
 '~': 'asciitilde'}
